GET  http://localhost:4000/posts
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVicmkiLCJpYXQiOjE2NTcwNjA4Mjl9.VgbG18CKYeiiA-v1u9NWBDViE6BqSh3u2GYbWirHYos
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "febri"
}
